### ISSUE TITLE
Bug in compute_dominance

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn-disclosure-control#25]
sorry, no reprex but here is the traceback

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\erikj\surfdrive\SoDa\projects\synthetic_data\metasynth-YOUth-pilot\synthesize.py", line 41, in metaframe_from_filename
    return MetaFrame.fit_dataframe(df=df_real, meta_config=config) #, dist_providers="metasynth-disclosure", privacy=DisclosurePrivacy())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\metasyn\metaframe.py", line 148, in fit_dataframe
    var = MetaVar.fit(
          ^^^^^^^^^^^^
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\metasyn\var.py", line 183, in fit
    distribution = provider_list.fit(series, var_type, dist_spec, privacy)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\metasyn\provider.py", line 226, in fit
    return self._find_best_fit(series, var_type, unique, privacy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\metasyn\provider.py", line 278, in _find_best_fit
    dist_instances = [d.fit(series, **privacy.fit_kwargs) for d in dist_list]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\metasyn\provider.py", line 278, in <listcomp>
    dist_instances = [d.fit(series, **privacy.fit_kwargs) for d in dist_list]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\surfdrive\SoDa\projects\synthetic_data\metasyn-disclosure-control\metasyncontrib\disclosure\numerical.py", line 16, in fit
    sub_series = micro_aggregate(pl_series, n_avg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\surfdrive\SoDa\projects\synthetic_data\metasyn-disclosure-control\metasyncontrib\disclosure\utils.py", line 83, in micro_aggregate
    sub_values, dominance = _create_subsample(values, *cur_settings)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\surfdrive\SoDa\projects\synthetic_data\metasyn-disclosure-control\metasyncontrib\disclosure\utils.py", line 49, in _create_subsample
    dominance = max(_compute_dominance(block_values, reverse=False),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\surfdrive\SoDa\projects\synthetic_data\metasyn-disclosure-control\metasyncontrib\disclosure\utils.py", line 24, in _compute_dominance
    return np.max(dominance)
           ^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amax
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\numpy\core\fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erikj\AppData\Roaming\Python\Python311\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by vankesteren** [comment]
seems to happen for series where constantdistribution would be appropriate
